name: Publish package to NPM

on:
    workflow_dispatch:
        inputs:
            packagePath:
                description: 'Package path'
                required: false
                default: './packages/sdk-core'
            testRefName:
                description: 'Test ref name'
                required: false
    push:
        tags:
            - '*/*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            # - name: Use Node.js ${{ matrix.node-version }}
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: ${{ matrix.node-version }}
            # - run: npm ci
            # - run: npm run build
            # - run: npm test
            - name: Get package path
              run: |
                  TEST_REF_NAME="${{ github.event.inputs.testRefName }}"
                  echo $TEST_REF_NAME
                  REF_NAME=${TEST_REF_NAME:-$GITHUB_REF_NAME}
                  echo $REF_NAME
                  PACKAGE_NAME="${REF_NAME/\/*/}"
                  echo $PACKAGE_NAME
                  PACKAGE_PATH=$(find ./packages ./tools -name "$PACKAGE_PATH" -maxdepth 1 -type d)
                  echo $PACKAGE_PATH
                  echo "TEST"
