name: Publish package to NPM

on:
    workflow_dispatch:
        inputs:
            packageName:
                description: 'Package name'
                required: true
            ref:
                description: 'Revision'
                required: false
    push:
        tags:
            - '*/*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.ref || github.ref_name }}
            - name: Get package path
              run: |
                  # Package name from workflow input
                  PACKAGE_NAME_VAR="${{ github.event.inputs.packageName }}"

                  # Set PACKAGE_NAME to either provided variable 
                  # or GITHUB_REF_NAME (e.g. sdk-core/0.1.2) with everything after "/" replaced
                  PACKAGE_NAME="${PACKAGE_NAME_VAR:-${GITHUB_REF_NAME/\/*/}}"

                  # Find PACKAGE_NAME in ./packages or ./tools and assign the path to PACKAGE_PATH
                  export PACKAGE_PATH=$(find ./packages ./tools -name "$PACKAGE_NAME" -maxdepth 1 -type d)

                  # Export PACKAGE_PATH to other steps
                  echo "PACKAGE_PATH=${PACKAGE_PATH}" >> $GITHUB_ENV

                  echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
                  echo "PACKAGE_NAME: $PACKAGE_NAME"
                  echo "PACKAGE_PATH: $PACKAGE_PATH"

            - name: Check if PACKAGE_PATH is set
              run: |
                  [[ -z "$PACKAGE_PATH" ]] && { echo "PACKAGE_PATH must be set."; exit 1; }
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm -w $PACKAGE_PATH run --if-present build
            - run: npm -w $PACKAGE_PATH run --if-present test
            # - run: npm -w $PACKAGE_PATH publish
