name: Publish package to NPM

on:
    workflow_dispatch:
        inputs:
            packagePath:
                description: 'Package path'
                required: false
                default: './packages/sdk-core'
            tag:
                description: 'Ref'
                required: false
    push:
        tags:
            - '*/*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.tag || github.ref_name }}
            # - name: Use Node.js ${{ matrix.node-version }}
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: ${{ matrix.node-version }}
            # - run: npm ci
            # - run: npm run build
            # - run: npm test
            - name: Get package path
              run: |
                  TEST_REF_NAME="${{ github.event.inputs.tag }}"
                  echo $TEST_REF_NAME
                  REF_NAME=${TEST_REF_NAME:-$GITHUB_REF_NAME}
                  echo $REF_NAME
                  PACKAGE_NAME="${REF_NAME/\/*/}"
                  echo $PACKAGE_NAME
                  PACKAGE_PATH_VAR="${{ github.event.inputs.packagePath }}"
                  export PACKAGE_PATH=${PACKAGE_PATH_VAR:-$(find ./packages ./tools -name "$PACKAGE_NAME" -maxdepth 1 -type d)}
                  echo "PACKAGE_PATH=${PACKAGE_PATH}" >> $GITHUB_ENV
            - name: Teest
              run: echo $PACKAGE_PATH
            # - name: Use Node.js ${{ matrix.node-version }}
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: ${{ matrix.node-version }}
            # - run: npm ci
            # - run: npm -w $PACKAGE_PATH run build
            # - run: npm -w $PACKAGE_PATH test
